version: "3.8"

services:
  database:
    container_name: database
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - .database/postgres/data:/var/lib/postgresql/data
